version: '3'

services:
  flaskapp:
    build: ./flask-server
    container_name: flaskapp
    ports:
      - "5000:5000"
    network_mode: host

  flaskapp2:
    build: ./flask-server2
    container_name: flaskapp2
    ports:
      - "3000:3000"
    network_mode: host

  nginx:
    build: ./nginx
    container_name: nginx
    environment:
       - SERVER_NAME=3.34.186.216
    restart: always
    network_mode: host

networks:
  default:
    driver: bridge
