version: '3'

services:

  reverse_proxy:
    image: nginx
    container_name: reverse_proxy
    depends_on:
      - flaskapp
      - flaskapp2
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    environment:
      - SERVER_NAME=3.35.137.21

        
  flaskapp:
    image: flaskapp
    build: ./flask-server
    container_name: flaskapp
    ports:
      - "5001:5001"
    network_mode: host
  
  flaskapp2:
    image: flaskapp2
    build: ./flask-server2
    container_name: flaskapp2
    ports:
      - "5002:5002"
    network_mode: host 
